# Generated by Django 5.0.6 on 2024-06-13 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BusinessCase", "0002_product_imageurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderhistory",
            name="product",
        ),
        migrations.RemoveField(
            model_name="orderhistory",
            name="user",
        ),
    ]
