# Generated by Django 5.0.6 on 2024-06-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BusinessCase", "0003_remove_orderhistory_product_remove_orderhistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="home_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
