# Generated by Django 5.0.6 on 2024-06-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BusinessCase", "0004_user_home_latitude_user_home_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
    ]
